Added remove game button
Greyewi/TableGames pull request #3
Opened 2020-10-19 22:16 UTC by olegover

2020-10-20 17:10 UTC, Greyewi requested changes

2020-10-20 17:10 UTC, Greyewi commented on src/components/Games/index.js
> +const Games = ({changeActiveGame, createGame, initGamesList, removeActiveGame, gamesList, ...props}) => {
это не нужно

2020-10-20 17:10 UTC, Greyewi commented on src/components/Games/index.js
> +      <GamesList handleChangeGame={changeActiveGame} gamesList={gamesList} removeActiveGame={removeActiveGame} {...props}/>
...props - тут все уже есть
поэтому этот кусок кода тоже не нужен

2020-10-23 00:10 UTC, olegover commented on src/components/Games/index.js
> +const Games = ({changeActiveGame, createGame, initGamesList, removeActiveGame, gamesList, ...props}) => {
Хотелось сделать чуть нагляднее..., а получилось как всегда(

2020-10-23 09:32 UTC, Greyewi approved these changes

2020-10-23 09:34 UTC, Greyewi commented
Осталось почикать конфликты)

2020-10-23 15:54 UTC, merged

2020-10-23 15:54 UTC, Greyewi commented
Почикал